# Generated by Django 6.0.2 on 2026-03-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_product_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='stock',
            new_name='stock_count',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='myapp.shop'),
        ),
    ]
