# Generated by Django 6.0.2 on 2026-03-03 05:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_stock_inventory_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), django.db.models.functions.text.Lower('weight'), name='unique_product_variant_case_insensitive'),
        ),
    ]
