# Generated by Django 6.0.2 on 2026-03-10 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('shop_created', 'Shop Created'), ('shop_updated', 'Shop Updated'), ('shop_deleted', 'Shop Deleted'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('inventory_added', 'Addded to Shop'), ('inventory_updated', 'Stock Updated'), ('inventory_removed', 'Removed from Shop'), ('password_changed', 'Password Changed')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
